### ISSUE TITLE
V1.0.0 Roadmap

### ISSUE THREAD

**Issue by mmiller-max** [JuliaTesting/TestReports.jl#48]
I think we're reasonably close to the `TestReports` being ready for V1.0.0. Here is an initial list of tasks for discussion.

### Functionality

- [x] `TestSet`s that use the `for` syntax result in multiple testsuites with the same name (will be fixed by testsuite/id below) #56 
- [x] Ensure all "required" fields in [schema](https://github.com/windyroad/JUnit-Schema/blob/master/JUnit.xsd) are present in report - main aim is that anything reading there report should have the fields that it expects
  - [x] testcase/time (? this is tricky to fill accurately, could be defaulted) #49 
  - [x] testsuite/time (This one we can do accurately by adding functionality to `ReportingTestSet`s) #49 
  - [x] testsuite/hostname (can default to `localhost`) #56
  - [x] testsuite/timestamp #49 
- [x] Other schema updates #56
  - [x] testsuite/id should be an `int` that increments for each test suite #56
  - [x] testsuites doesn't need id #56
- [x] Fix compatibility with `CustomTestSet`s #61

### Docs

- [ ] Update document examples when all schema updates done #60 
- [ ] Review docs for grammar/clarity etc #60 

### CI

- [x] Only test PRs and master, rather than all branches (completed by #52)

### Code Hygiene

- [x] Ensure all internal functions have docstrings #58 
- [x] Refactor the larger functions in `runner`, e.g. `test!` #58 
- [x] Split out `runtests.jl` into different files for different bits of functionality #59 
- [x] Move `import`/`using` to the `TestRepots.jl` file #69

### Not for V1.0.0
- pass information, relies on [updates](https://github.com/JuliaLang/julia/pull/36879) to Julia
- It would be nice to rely less on `Pkg` internals, but I'm not sure how possible this is without re-writing lots of it ourselves

**Comment by oxinabox** [comment]
We have now tagged 1.0
